# This should be the minium RBAC that is needed for users (not operators) to
# use telepresence.  These objects are used in a portion of our tests to
# determine if we have changed the minimal rbac profile. If you need to change
# this file, you must also change it in the docs.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telepresence-agent-injector
rules:
- apiGroups:
  - ""
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: telepresence-agent-injector
subjects:
- kind: User
  name: system:serviceaccount:ambassador:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: telepresence-agent-injector
  apiGroup: rbac.authorization.k8s.io
